# Generated by Django 6.0.3 on 2026-03-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number']},
        ),
    ]
