# Generated by Django 6.0.3 on 2026-03-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_date_of_joining_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-id']},
        ),
    ]
