# Generated by Django 6.0.3 on 2026-03-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroutine',
            options={'ordering': ['school_class', 'section', 'day', 'period']},
        ),
    ]
