# Generated by Django 6.0.3 on 2026-03-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['school_class', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
    ]
