# Generated by Django 6.0.3 on 2026-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicsession_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
