# Generated by Django 6.0.3 on 2026-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_options_subject_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_objective',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_written',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_objective',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_practical',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_written',
            field=models.FloatField(default=100),
        ),
    ]
