# Generated by Django 6.0.3 on 2026-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late Entry'), ('EL', 'Early Leave'), ('A', 'Absent'), ('LE', 'Leave')], max_length=5),
        ),
    ]
