# Generated by Django 6.0.3 on 2026-03-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicsession_is_active'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='academics.class'),
        ),
    ]
