# Generated by Django 6.0.3 on 2026-04-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_frequency_feestructure_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['school_class', 'name']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id']},
        ),
    ]
