# Generated by Django 6.0.3 on 2026-04-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feestructure_options_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['id']},
        ),
    ]
