# Generated by Django 6.0.3 on 2026-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_logout_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
